import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import { Toaster } from "sonner";
import { UserMenu } from "@/components/user-menu";
import { auth } from "@/lib/auth/auth";
import "@/lib/api-client";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b">
          <div className="container mx-auto px-4 py-4">
            {session?.user?.name && <UserMenu userName={session.user.name} />}
          </div>
        </header>
        {children}
        <Toaster
          richColors
          duration={2000}
          position="bottom-right"
          offset={{ top: 50 }}
          closeButton
        />
      </body>
    </html>
  );
}
