import type { RequestHandler } from "msw";
import { autoGeneratedHandlers } from "./mocker";
import { serverDetailHandlers } from "./server-detail";
import { vmcpHandlers } from "@/features/vmcp-builder/mocks/handlers";

// Scenarios are now handled via the x-mock-scenario header in AutoAPIMock.generatedHandler
// See src/mocks/scenarioNames.ts for available scenarios

export const handlers: RequestHandler[] = [
  ...vmcpHandlers,
  ...serverDetailHandlers,
  ...autoGeneratedHandlers,
];
