import type { RequestHandler } from "msw";
import { autoGeneratedHandlers } from "./mocker";
import { emptyServersHandlers } from "./scenarios/empty-servers";
import { serverDetailHandlers } from "./server-detail";

export const handlers: RequestHandler[] = [
  // Scenario handlers (cookie-activated) - must come first
  ...emptyServersHandlers,
  // Custom handlers
  ...serverDetailHandlers,
  // Auto-generated handlers (fallback)
  ...autoGeneratedHandlers,
];
